### ISSUE TITLE
Criar card de apresentação do projeto

### ISSUE THREAD

**Issue by Gustavo-Macedo1** [Gustavo-Macedo1/Hackathon-LLama-Impact#8]

**Comment by rabelomanager** [comment]
Deixe-me comentar a descrição da solução do ponto de vista da apresentação. Gostaria de ver o objetivo claro da solução, talvez no título. Você pode dividir as entregas do MVP, as coisas que você pode construir no escopo do hackathon e as metas de longo prazo que você pode trabalhar depois de ter o MVP. Começar com CSV é totalmente aceitável na minha opinião, é bom focar na solução em si e trabalhar em um produto maior depois de mostrar sua viabilidade no hackathon. Se você tiver algum CSV para testar sua solução, vá em frente e crie o mais rápido possível
